### ISSUE TITLE
4.3.2版本求搭救

### ISSUE THREAD

**Issue by jingliancui** [hug3id/Xamarin.Forms.BaiduMaps#12]
你好，我今天去官方看了一下，已经更新到4.3.2了，我自己尝试去做binding，可是被那些混淆搞到头晕脑胀了。能搭救一下吗。。。。

**Comment by l2999019** [comment]
我也是这样,而且产生了大量的乱码BUG
![image](https://user-images.githubusercontent.com/10385855/29553054-58c9894c-874c-11e7-90e4-44f16b035c8b.png)
