### ISSUE TITLE
定位报错为：location failed:505

### ISSUE THREAD

**Issue by caoxiaobo136** [hug3id/Xamarin.Forms.BaiduMaps#6]
根据代码中的sample.cs编写例子，运行后定位报错为：location failed:505，地图也没有显示，显示空白！怎么解决阿？

**Comment by hug3id** [comment]
505 key错误，请按说明填上正确的百度开发key

**Comment by caoxiaobo136** [comment]
对的，我的编译的包名跟百度上的包名不一致，填写一致就行了，谢谢！
