### ISSUE TITLE
做地理编码的时候总是返回permissionunfinished

### ISSUE THREAD

**Issue by jingliancui** [hug3id/Xamarin.Forms.BaiduMaps#8]
`BMKGeoCodeSearch search = new BMKGeoCodeSearch();`
           ` search.Init();     `       
`            search.Delegate = new CustomBMKGeoCodeSearchDelegate();`
 `           var option = new BMKGeoCodeSearchOption()`
            `{`
             `   City="北京市",`
`                Address= "海淀区上地10街10号"`
 `           };`
  `          search.GeoCode(option);`
`            option.Dispose();`

虽然我已经在appdelegate那的bmkmapmanager那的两个回调里，返回0(没问题)给我了。
当我调用地理编码相关函数时总是给我返回permissionunfinished

**Comment by hug3id** [comment]
我在最新版1.3.1上做实验发现返回正常，坐标[40.0568901279313, 116.308150630071]
我能想到可能有的问题有：
1. info.plist 中是否有添加 Bundle display name
2. 鉴权是异步的，是否在鉴权之前就调用了搜索功能
3. 百度API控制台中对应的key是否有钩上地理编码服务

**Comment by jingliancui** [comment]
你好啊，我的是xamarin.ios项目。key没有问题
流程是这样的:
1.vs新建ios项目。
2.直接引用你的ios的binding项目并成功生成90多MB的dll文件。
3.ios项目引用dll文件。
4.BMKMapManager实行初始化，并在回调函数ongetnetwork和ongetpermission得到的都是0(表示ok)。
5.实例化地理编码类BMKGeoCodeSearch并初始化后，调用GeoCode函数。
6.回调却返回permissionunfinished状态码。

以下是我的mtouch参数:
-gcc_flags "-L${ProjectDir} -framework MapKit -framework CoreMotion -framework CoreGraphics -framework QuartzCore -framework CoreText -framework CoreLocation -framework SystemConfiguration -framework CoreTelephony -framework OpenGLES -framework Foundation -framework Security -lz -lstdc++.6.0.9 -lsqlite3.0 -ObjC"

以下是我在info.plist文件的键值对：
```
<key>CFBundleDisplayName</key>
<string>XamarinSample</string>

<key>CFBundleName</key>
<string>XamarinSample</string>

<key>CFBundleIdentifier</key>
<string>com.companyname.xamarinsample</string>
	

<key>LSApplicationQueriesSchemes</key>
<array>
<string>baidumap</string>
</array>

<key>NSLocationWhenInUseUsageDescription</key>
<string></string>

<key>NSAppTransportSecurity</key>
<dict>
   <key>NSAllowsArbitraryLoads</key>
   <true />
</dict>
```
另外的我知道安卓的没有问题，因为上一年的时候安卓的我已经调试通过。

**Comment by hug3id** [comment]
我的环境是Xamarin 6.3，新建 Xamarin.iOS 直接引用最新Binding项目，mtouch 参数空，info.plist 增加 Bundle display name，appid com.booway.test。ViewController.cs 如下：

`class GeneralDelegate : BMKGeneralDelegate
    {
    	public override void OnGetNetworkState(int iError)
    	{
    		Debug.WriteLine("OnGetNetworkState: " + iError);
    	}

    	public override void OnGetPermissionState(int iError)
    	{
    		Debug.WriteLine("OnGetPermissionState: " + iError);
        }
    }

    class GeoCodeSearchDelegate : BMKGeoCodeSearchDelegate
    {
        public override void OnGetGeoCodeResult(BMKGeoCodeSearch searcher, BMKGeoCodeResult result, BMKSearchErrorCode error)
        {
            Debug.WriteLine(result.Location);
        }
    }

    public partial class ViewController : UIViewController
    {
        protected ViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.

            BMKMapManager mgr = new BMKMapManager();
            mgr.Start("B3iCnaZ9pv6UDbenWBEHdfY36dsVLUnM", new GeneralDelegate());

            UIButton btn = new UIButton {Frame = new CGRect(0, 0, 100, 100)};
            btn.BackgroundColor = UIColor.Red;
            btn.SetTitle("search", UIControlState.Normal);
            View.AddSubview(btn);
            btn.AddTarget((sender, e) => {
                BMKGeoCodeSearch search = new BMKGeoCodeSearch();
                search.Init();
                search.Delegate = new GeoCodeSearchDelegate();
                search.GeoCode(new BMKGeoCodeSearchOption { City = "北京市", Address = "海淀区上地10街10号" });
            }, UIControlEvent.TouchUpInside);
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
        }
    }`

点击按键输出如下：
OnGetNetworkState: 0
OnGetPermissionState: 0
(Latitude=40.0568901279313, Longitude=116.308150630071
(Latitude=40.0568901279313, Longitude=116.308150630071

**Comment by jingliancui** [comment]
你好！我解决了！
原因是因为
```
var BaiduMapMgr = new BMKMapManager();
BaiduMapMgr.Init();
```
写多了一句`BaiduMapMgr.Init();`
去掉之后search包的功能ok了。
我也想知道为什么会这样。
因为我看官方的demo是带上调用Init函数的，所以我就跟着在xamarin上带上Init函数了。

**Comment by hug3id** [comment]
官方例子是：_mapManager = [[BMKMapManager alloc]init];  
等效于 var _mapManager = new BMKMapManager();
Init函数是自动调用的，不用再次手动调用。
下面 BMKGeoCodeSearch search = new BMKGeoCodeSearch(); 也是，不需调用 Init()
